{
 "title": "JVM Metrics - REST Services Benchmark",
 "tags": [
  "jvm",
  "benchmark",
  "prof-lachgar"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "Heap Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_heap_used{job=~\"jersey|springmvc|springdata\"}",
     "legendFormat": "{{service}} - Used"
    },
    {
     "expr": "jvm_memory_heap_max{job=~\"jersey|springmvc|springdata\"}",
     "legendFormat": "{{service}} - Max"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "CPU" }
   ],
   "targets": [
    {
     "expr": "jvm_ProcessCpuLoad{job=~\"jersey|springmvc|springdata\"} * 100",
     "legendFormat": "{{service}} - CPU %"
    }
   ]
  },
  {
   "title": "GC Collection Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Collections/sec" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_count{job=~\"jersey|springmvc|springdata\"}[1m])",
     "legendFormat": "{{service}} - {{gc}}"
    }
   ]
  },
  {
   "title": "GC Collection Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_time_ms{job=~\"jersey|springmvc|springdata\"}[1m])",
     "legendFormat": "{{service}} - {{gc}}"
    }
   ]
  },
  {
   "title": "Thread Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Threads" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_ThreadCount{job=~\"jersey|springmvc|springdata\"}",
     "legendFormat": "{{service}} - Total"
    },
    {
     "expr": "jvm_threads_DaemonThreadCount{job=~\"jersey|springmvc|springdata\"}",
     "legendFormat": "{{service}} - Daemon"
    }
   ]
  },
  {
   "title": "HikariCP Connection Pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "hikaricp_ActiveConnections{job=~\"jersey|springmvc|springdata\"}",
     "legendFormat": "{{service}} - Active"
    },
    {
     "expr": "hikaricp_IdleConnections{job=~\"jersey|springmvc|springdata\"}",
     "legendFormat": "{{service}} - Idle"
    },
    {
     "expr": "hikaricp_ThreadsAwaitingConnection{job=~\"jersey|springmvc|springdata\"}",
     "legendFormat": "{{service}} - Waiting"
    }
   ]
  },
  {
   "title": "Non-Heap Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_nonheap_used{job=~\"jersey|springmvc|springdata\"}",
     "legendFormat": "{{service}} - Used"
    }
   ]
  },
  {
   "title": "Classes Loaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Classes" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_LoadedClassCount{job=~\"jersey|springmvc|springdata\"}",
     "legendFormat": "{{service}} - Loaded"
    }
   ]
  }
 ]
}